# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    #- go mod download
    # you may remove this if you don't need go generate
    #- go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  binary: "share"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
brew:
  github:
    owner: mschneider82 
    name: sharecmd
  folder: Formula
  homepage: https://github.com/mschneider82/sharecmd
  description: Share your files with your friends using Cloudproviders with just one command.
nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage: https://github.com/mschneider82/sharecmd
  description: Share your files with your friends using Cloudproviders with just one command.
  maintainer: Matthias Schneider <ms@wck.biz>
  license: Apache
  formats:
  - deb
  - rpm
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
